from pathlib import Path
BASE_PATH = Path().absolute()


STORIES_SERVICE_IP = '0.0.0.0'
STORIES_SERVICE_PORT = '5001'

USERS_SERVICE_IP = '0.0.0.0'
USERS_SERVICE_PORT = '5002'

FOLLOWERS_SERVICE_IP = '0.0.0.0'
FOLLOWERS_SERVICE_PORT = '5003'